book_exchanger/urls.py
from django.contrib import admin
from django.urls import path, re_path
from book_exchanger.views import *
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework import viewsets

app_name = 'book_exchanger'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('index/', index, name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('outcoming/', OutcomingRequestsView.as_view(), name='outcoming'),
    path('incoming/', IncomingRequestsView.as_view(), name='incoming'),
    path('search/', search_books, name='search'),
    path('my_books/', UserBookList.as_view(), name='my_books'),
    path('get_book_owners/<int:book_id>/', get_book_owners, name='get_book_owners'),
    path('add_book_instance/<int:book_id>/', add_book_instance, name='add_book_instance'),
    path('success/', SuccessVew.as_view(), name='success'),
    path('add_book/', add_book, name='add_book'),
    path('request_book_instance/<int:instance_id>', request_book, name='request_book_instance'),
    re_path(r'^book_instance/(?P<pk>[\w-]+)/$', BookInstanceDeleteView.as_view(),
            name='book_delete'),
    path('decline_request/<int:request_id>', decline_request, name='decline_request'),
    path('approve_request/<int:request_id>', approve_request, name='approve_request'),
    path('process_request/<int:request_id>', process_request, name='process_request'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('profile/', view_profile, name='profile')
]

exchange_net/urls.py
from django.contrib import admin
from django.urls import path, include
from book_exchanger.views import *
from .api import router
import djoser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_exchanger/', include('book_exchanger.urls')),
    path('reviews/', include('reviews.urls')),
    path('index/', index, name='index'),
    path('api/v1/', include(router.urls)),
    path('api/auth/', include('djoser.urls.authtoken')),
]

reviews/urls.py
from django.contrib import admin
from django.urls import path
from book_exchanger.views import *
from django.contrib.auth.views import LogoutView
from reviews.views import *
app_name = 'reviews'
urlpatterns = [
    path('all/', BookReviewListView.as_view(), name='all'),
    path('add_review/<int:book_id>/', add_review, name='add_review'),

]

reviews/models.py
from django.db import models
from book_exchanger.models import *


# Create your models here.
class Review(models.Model):
    description = models.TextField(max_length=200)
    title = models.CharField(max_length=20, null=True)
    author = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = "review"


class BookReview(Review):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "book review"
        db_table = "book_review"


class UserReview(Review):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "user review"
        db_table = "user_review"


class ReviewComment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    text = models.TextField(40)

    class Meta:
        verbose_name = "review comment"
        db_table = "review_comment"

reviews/forms.py
from django import forms
from book_exchanger.models import *
from django.utils.translation import gettext_lazy as _
from reviews.models import *


class BookReviewForm(forms.Form):
    description = forms.CharField(required=True, widget=forms.Textarea)
    book_id = forms.IntegerField(widget=forms.HiddenInput)
    title = forms.CharField(required=True)


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = ReviewComment
        fields = ['text']

reviews/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from book_exchanger.forms import *
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.forms import ModelForm
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, F
from django.views import View
from django.views.generic import TemplateView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from reviews.forms import *


# Create your views here.
@login_required(login_url=reverse_lazy('book_exchanger:login'))
def add_review(request, book_id):
    if request.method == "POST":
        form = BookReviewForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            book_id = form.cleaned_data['book_id']
            BookReview.objects.create(title=title, description=description, book_id=book_id,
                                      author=request.user)
            return redirect('book_exchanger:success')
    else:
        form = BookReviewForm()
        return render(request, "review_form.html", {'form': form, 'book_id': book_id})


class BookReviewListView(ListView):
    model = BookReview
    context_object_name = 'book_review_list'
    template_name = 'book_reviews.html'
    queryset = BookReview.objects.all()

templates/add_book.html
{% extends "base.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container jumbotron">
        <div class="row">
            <h1 class="col-md-6">Новая книга:</h1>
            <form action="{% url "book_exchanger:add_book" %}" method="post" class="col-md-12">
                {% csrf_token %}
                <div class="form-group col-md-6 mb-0">
                    {{ form.title|as_crispy_field }}<br>
                    {% for error in form.title.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.author|as_crispy_field }}<br>
                    {% for error in form.author.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    <button type="submit" class="btn btn-outline-success">Добавить</button>
                </div>
                {% if message %}
                    <div class="alert-danger">
                        {{ message }}
                    </div>
                {% endif %}
                    <div class="alert-danger">
                        {{ form.errors }}
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href=" {% static "css/styles.css" %}">
    <title>{{ title }}</title>
    {% if request.user.is_authenticated %}
    <style>
        body {
            background-image: url("{% static "css/books.jpg"%}");
        }
    </style>
    {% endif %}
</head>
<body>
<header>
    <nav class="navbar navbar-light bg-light">
        {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url "book_exchanger:profile" %}">{{ request.user.username }}</a>
        {% else %}
            <a class="navbar-brand" href="/">BookExchanger</a>
        {% endif %}
        {% if request.user.is_authenticated %}
            <div class="btn-group" role="group">
            <div class="dropdown">
                <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Заявки
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url "book_exchanger:outcoming" %}">Исходящие</a>
                    <a class="dropdown-item" href="{% url "book_exchanger:incoming" %}">Входящие</a>
                </div>
            </div>
            <div class="dropdown">
                <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Книги
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url "book_exchanger:my_books" %}">Мои книги</a>
                    <div class="dropdown-divider"></div>
                    <form class="dropdown-item form-inline" action="{% url "book_exchanger:search" %}" method="POST">
                        {% csrf_token %}
                        <input class="search-field form-control form-control-md" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q">
                    </form>

                </div>
            </div>
            <a class="btn btn-outline-dark " href="{% url "reviews:all" %}">Обзоры </a>
            <a class="btn btn-outline-danger " href="{% url "book_exchanger:logout" %}">Выйти</a>
        {% else %}
            <p>
                <a class="btn btn-outline-dark " href="{% url "reviews:all" %}">Обзоры </a>
                <a class="btn btn-outline-primary " href="{% url "book_exchanger:signup" %}">Зарегистрироваться</a>
                <a class="btn btn-outline-success" href="{% url "book_exchanger:login" %}">Войти</a>
            </p>
        {% endif %}
        </div>
    </nav>
</header>
<!-- Begin page content -->
<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
<footer class="footer">
    <div class="container">
        <ul class="nav">
            <li class="nav-item">
                <span class="text-muted nav-link">Book Exchanger 2020 (c). Все права защищены.</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">О нас</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://vk.com/knaxi">Обратная связь</a>
            </li>
            <li class="nav-item">
                <span class="text-muted nav-link">Лицензия MIT/X11.</span>
            </li>
        </ul>
    </div>
</footer>
</body>
</html>

templates/book_reviews.html
{% extends 'base.html' %}
{% block content %}
{% for review in book_review_list %}
    <div class="container jumbotron">
        <h3>{{ title }}</h3>
        <h4>Обзор на книгу:  "{{ review.book.title }}"</h4>
        {{ description }}
        <h3>Автор:  {{ review.author.nickname }}</h3>
    </div>
{% endfor %}

{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div class="row">
            <h1 class="col-md-6">Редактирование профиля</h1>
            <form action="{% url "book_exchanger:edit_profile" %}" method="post" class="col-md-12">
                {% csrf_token %}
                <div class="form-group col-md-6 mb-0">
                    {{ form.name|as_crispy_field }}<br>
                    {% for error in form.name.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.surname|as_crispy_field }}<br>
                    {% for error in form.surname.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.bio|as_crispy_field }}<br>
                    {% for error in form.bio.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    <button type="submit" class="btn btn-outline-success">Сохранить</button>
                </div>
                {% if message %}
                    <div class="alert-danger">
                        {{ message }}
                    </div>
                {% endif %}
                    <div class="alert-danger">
                        {{ form.errors }}
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron justify-content-center">
        <button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="Popover title" data-content="{{ error }}">
            Что случилось?</button>
    </div>
{% endblock %}

templates/incoming.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
    <ul class="list-group">
        {% for request in requests %}
        <li class="list-group">{{ request.requestant.username}}
            <br>Email: {{ request.requestant.email }}
            <br>Статус: {{ request.status }}</li>
            {% if request.status == "На рассмотрении" %}
            <a class="btn-outline-danger" href="{% url 'book_exchanger:decline_request' request.id %}">Отклонить</a>
            <a class="btn-outline-success" href="{% url 'book_exchanger:approve_request' request.id %}">Одобрить</a>
            {% endif %}
        {% endfor %}
    </ul>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Приветствуем в Book Exchanger!</h1>
        <p class="lead">Наш проект призван упростить обмен книгами между незнакомыми людьми.</p>
        <hr class="my-4">
        <a class="btn btn-outline-dark btn-lg" href="http://vk.com/book_exchanger" role="button">Подробнее о нас в ВК</a>
    </div>
{% endblock %}

templates/mybooks.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <div class="justify-content-center">
        {% for instance in books %}
            <div class="card" style="width: 18rem;">
                <img src="{% static 'css/icon.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ instance.book.title }}</h5>
                    <p class="card-text">За
                        авторством: {{ instance.book.author.name }} {{ instance.book.author.surname }}</p>
                    <a href="{% url "book_exchanger:book_delete" instance.id %}" class="btn btn-primary">Удалить</a>
                    <a href="{% url 'reviews:add_review' instance.book.id %}" class="btn btn-primary">Написать обзор</a>
                </div>
            </div>
        {% endfor %}
        <div>
            <a class="btn btn-primary" href="{% url "book_exchanger:add_book" %}">Добавить книгу</a>
        </div>
    </div>
{% endblock %}

templates/outcoming.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
    <ul class="list-group">
        {% for request in requests %}
        <li class="list-group">{{ request.owner.username}}
            <br> Статус: {{ request.status }}</li>
            {% if request.status == "На оформлении" %}
            <a class="btn-outline-success" href="{% url 'book_exchanger:process_request' request.id %}">Оформить</a>
            {% endif %}
        {% endfor %}
    </ul>
    </div>
{% endblock %}

templates/owners.html
{% extends 'base.html' %}
{% block content %}
    {% for instance in instances %}
        <div class="justify-content-center">
            <h1>Данная книга есть у:</h1>
            <div class="list-group">
                <a href="{% url 'book_exchanger:request_book_instance' instance.id %}" class="list-group-item list-group-item-action">{{ instance.owner.username }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="container jumbotron">
        <h1>Вот что мы знаем о Вас:</h1>
        Имя: {{ request.user.profile.name }}
        Фамилия: {{ request.user.profile.surname }}
        О себе: {{ request.user.profile.bio }}
        <a class="btn-outline-success" href="{% url "book_exchanger:edit_profile" %}">Изменить профиль</a>
    </div>
{% endblock %}

templates/registration.html
{% extends "base.html" %}

{% block content %}

    {% load crispy_forms_tags %}
    <div class="container">
        <div class="row">
            <h1 class="col-md-6">Регистрация</h1>
            <form action="{% url "book_exchanger:signup" %}" method="post" class="col-md-12">
                {% csrf_token %}
                <div class="form-group col-md-6 mb-0">
                    {{ form.email|as_crispy_field }}<br>
                    {% for error in form.email.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.username|as_crispy_field }}<br>
                    {% for error in form.username.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.password|as_crispy_field }}<br>
                    {% for error in form.password.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.password_again|as_crispy_field }}<br>
                    {% for error in form.password_again.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    <button type="submit" class="btn btn-outline-success">Регистрация</button>
                </div>
                {{ message }}
            </form>
        </div>
    </div>
{% endblock %}

templates/review_form.html
{% extends "base.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container jumbotron">
        <div class="row">
            <h1 class="col-md-6">Новый обзор:</h1>
            <form action="{% url "reviews:add_review" book_id %}" method="post" class="col-md-12">
                {% csrf_token %}
                <div class="form-group col-md-6 mb-0">
                    {{ form.title|as_crispy_field }}<br>
                    {% for error in form.title.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.description|as_crispy_field }}<br>
                    {% for error in form.description.errors %}
                        <p class="alert alert-danger" role="alert">
                            {{ error }}
                        </p>
                    {% endfor %}
                </div>
                <div class="form-group col-md-6 mb-0">
                    <input type="hidden" value="{{ book_id }}" name="book_id">
                </div>
                <div class="form-group col-md-6 mb-0">
                    <button type="submit" class="btn btn-outline-success">Добавить</button>
                </div>
                {% if message %}
                    <div class="alert-danger">
                        {{ message }}
                    </div>
                {% endif %}
                    <div class="alert-danger">
                        {{ form.errors }}
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/search_result.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    {% for book in books %}
        <div class="card" style="width: 18rem;">
            <img src="{% static "css/icon.png" %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p class="card-text">Книга за авторством: {{ book.author.name }} {{ book.author.surname }}</p>
                <a href="{% url "book_exchanger:get_book_owners" book.id %}" class="btn btn-primary">Просмотреть владельцев</a>
                <a href="{% url "book_exchanger:add_book_instance" book.id%}" class="btn btn-primary">У меня тоже есть</a>
                <a href="{% url "reviews:add_review" %}" class="btn btn-primary">Написать отзыв</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}